name: DEPLOY DEV

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
jobs:
    deploy-prod:
        uses: KevPoirier/actions/.github/workflows/trigger-deploy.yml@main
        with:
          image_tag: ${{ inputs.tag }}
          service_name: hello
        secrets:
          gitops_pat: ${{ secrets.GITOPS_PAT }}
